{
 "title": "Service Availability",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "ProductConstructionService (Maestro)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "PCS Most Frequent Exceptions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "exceptions\r\n| where $__timeFilter(timestamp)\r\n| project Exception=problemId, Type=outerType\r\n| summarize Count=count() by Exception, Type\r\n| order by Count desc",
      "resource": "[parameter(product-construction-service-appinsights-resourcepath)]"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "database": "engineeringdata",
     "subscription": "[parameter(dotnet-eng-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "PCS Work Item Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customEvents\r\n| where name == \"WorkItemExecuted\" and $__timeFilter(timestamp)\r\n| extend Success = tobool(customDimensions[\"Success\"])\r\n| summarize Successful = countif(Success == true), Failed = countif(Success == false) by bin(timestamp, $__interval)\r\n| order by timestamp asc",
      "resource": "[parameter(product-construction-service-appinsights-resourcepath)]",
      "resultFormat": "time_series",
      "workspace": "[parameter(default-workspace-resourcepath)]"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "[parameter(dotnet-eng-appinsights-subscriptionid)]",
     "subscriptions": [
      "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
      "cab65fc3-d077-467d-931f-3932eabf36d3"
     ]
    },
    {
     "azureLogAnalytics": {
      "query": "customEvents\r\n| where name == \"WorkItemExecuted\" and $__timeFilter(timestamp)\r\n| extend Success = tobool(customDimensions[\"Success\"])\r\n| summarize SuccessRate=100*countif(Success == true)/count() by bin(timestamp, $__interval)\r\n| order by timestamp asc",
      "resource": "[parameter(product-construction-service-appinsights-resourcepath)]",
      "resultFormat": "time_series",
      "workspace": "[parameter(default-workspace-resourcepath)]"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "[parameter(dotnet-eng-appinsights-subscriptionid)]",
     "subscriptions": [
      "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
      "cab65fc3-d077-467d-931f-3932eabf36d3"
     ]
    }
   ]
  },
  {
   "title": "PCS Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "exceptions\r\n| where $__timeFilter(timestamp) and problemId !contains \"SpaDefaultPageMiddleware\"\r\n| summarize Exceptions=count() by bin(timestamp, $__interval)\r\n| order by timestamp asc",
      "resource": "[parameter(product-construction-service-appinsights-resourcepath)]",
      "resultFormat": "time_series",
      "workspace": "[parameter(default-workspace-resourcepath)]"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "[parameter(dotnet-eng-appinsights-subscriptionid)]",
     "subscriptions": [
      "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
      "cab65fc3-d077-467d-931f-3932eabf36d3"
     ]
    }
   ]
  },
  {
   "title": "PCS Work Item Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customEvents\r\n| where name == \"WorkItemExecuted\" and $__timeFilter(timestamp)\r\n| extend Type=tostring(customDimensions[\"WorkItemType\"])\r\n| summarize Count=count() by bin(timestamp, $__interval), Type=replace_string(Type, \"WorkItem\", \"\")\r\n| order by timestamp asc",
      "resource": "[parameter(product-construction-service-appinsights-resourcepath)]",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "database": "engineeringdata",
     "subscription": "[parameter(dotnet-eng-appinsights-subscriptionid)]"
    },
    {
     "azureLogAnalytics": {
      "query": "customEvents\r\n| where name == \"WorkItemExecuted\"\r\n| summarize TotalCount=count() by bin(timestamp, $__interval)\r\n| order by timestamp asc",
      "resource": "[parameter(product-construction-service-appinsights-resourcepath)]",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "database": "engineeringdata",
     "subscription": "[parameter(dotnet-eng-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "PCS Unhandled Work Items",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customEvents\r\n| where $__timeFilter(timestamp)\r\n| where name == \"WorkItemExecuted\"\r\n| extend attempt = toint(customDimensions[\"Attempt\"]), success = tobool(customDimensions[\"Success\"])\r\n| where success != true and attempt == 3\r\n| project timestamp, operation = operation_Name, operationId = operation_Id",
      "resource": "[parameter(product-construction-service-appinsights-resourcepath)]"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "database": "engineeringdata",
     "subscription": "[parameter(dotnet-eng-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "PSC work item attempts",
   "type": "timeseries",
   "description": "Count of attempts to process a specific PCS work item",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customEvents\r\n| where name == \"WorkItemExecuted\" and $__timeFilter(timestamp)\r\n| extend Attempt = customDimensions[\"Attempt\"]\r\n| summarize 1st = countif(Attempt == 1), 2nd = countif(Attempt == 2), 3rd = countif(Attempt == 3) by bin(timestamp, $__interval)\r\n| order by timestamp asc",
      "resource": "[parameter(product-construction-service-appinsights-resourcepath)]",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "[parameter(dotnet-eng-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "PCS Unhandled Workitems",
   "type": "timeseries",
   "description": "Number of PCS work items with unhandled exceptions, even after retries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customEvents\r\n| where name == \"WorkItemExecuted\" and $__timeFilter(timestamp)\r\n| extend Success = tostring(customDimensions[\"Success\"])\r\n| extend Attempt = toint(customDimensions[\"Attempt\"])\r\n| where Success == \"False\" and Attempt == 3\r\n| summarize TotalCount=count() by bin(timestamp, $__interval)\r\n| order by timestamp asc",
      "resource": "[parameter(product-construction-service-appinsights-resourcepath)]"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "[parameter(dotnet-product-construction-services-subscriptionid)]"
    }
   ]
  },
  {
   "title": "PCS Background Queue Wait Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Wait time (max)",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "pcs.queue.wait_time",
      "customNamespace": "Azure.ApplicationInsights",
      "metricNamespace": "Microsoft.Insights/components",
      "resourceGroup": "[parameter(product-construction-service-resourcegroup)]",
      "resourceName": "[parameter(product-construction-service-appinsights-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(dotnet-product-construction-services-subscriptionid)]"
    }
   ]
  },
  {
   "title": "PCS Failed Pull Request Updates",
   "type": "timeseries",
   "description": "Number of Pull Request Updates failed by PCS (this just includes things like title and description, not the code)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customEvents\r\n| where name == \"PullRequestUpdateFailed\"\r\n| summarize TotalCount=count() by bin(timestamp, $__interval)\r\n| order by timestamp asc",
      "resource": "[parameter(product-construction-service-appinsights-resourcepath)]"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "[parameter(dotnet-eng-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "PCS Work Item Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customEvents\r\n| where name == \"WorkItemExecuted\" and $__timeFilter(timestamp)\r\n| extend Duration = toint(customMeasurements[\"Duration\"])\r\n| summarize Duration = max(Duration) by bin(timestamp, $__interval)\r\n| order by timestamp asc",
      "resource": "[parameter(product-construction-service-appinsights-resourcepath)]",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "database": "engineeringdata",
     "subscription": "[parameter(dotnet-eng-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "PCS Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "[parameter(emptystring)]"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "requests/duration",
      "metricNamespace": "Microsoft.Insights/components",
      "resourceGroup": "[parameter(product-construction-service-resourcegroup)]",
      "resourceName": "[parameter(product-construction-service-appinsights-resourcename)]",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": ""
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "[parameter(dotnet-product-construction-services-subscriptionid)]",
     "subscriptions": [
      "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
      "cab65fc3-d077-467d-931f-3932eabf36d3"
     ]
    }
   ]
  },
  {
   "title": "PCS CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Virtual CPUs",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "performanceCounters/processCpuPercentage",
      "metricNamespace": "Microsoft.Insights/components",
      "resourceGroup": "[parameter(product-construction-service-resourcegroup)]",
      "resourceName": "[parameter(product-construction-service-appinsights-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(dotnet-product-construction-services-subscriptionid)]"
    }
   ]
  },
  {
   "title": "PCS HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "requests\r\n| where $__timeFilter(timestamp)\r\n| summarize 2xx=countif(toint(resultCode)/100 == 2) by bin(timestamp, $__interval)\r\n| order by timestamp asc",
      "resource": "[parameter(product-construction-service-appinsights-resourcepath)]"
     },
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Virtual CPUs",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "performanceCounters/processCpuPercentage",
      "metricNamespace": "Microsoft.Insights/components",
      "resourceGroup": "[parameter(product-construction-service-resourcegroup)]",
      "resourceName": "[parameter(product-construction-service-appinsights-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(dotnet-product-construction-services-subscriptionid)]"
    },
    {
     "azureLogAnalytics": {
      "query": "requests\r\n| where $__timeFilter(timestamp)\r\n| summarize 3xx=countif(toint(resultCode)/100 == 3), 4xx=countif(toint(resultCode)/100 == 4), 5xx=countif(toint(resultCode)/100 == 5) by bin(timestamp, $__interval)\r\n| order by timestamp asc",
      "resource": "[parameter(product-construction-service-appinsights-resourcepath)]"
     },
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Virtual CPUs",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "performanceCounters/processCpuPercentage",
      "metricNamespace": "Microsoft.Insights/components",
      "resourceGroup": "[parameter(product-construction-service-resourcegroup)]",
      "resourceName": "[parameter(product-construction-service-appinsights-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(dotnet-product-construction-services-subscriptionid)]"
    }
   ]
  },
  {
   "title": "PCS Git Clones",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customEvents\r\n| where name == \"GitClone\" and $__timeFilter(timestamp)\r\n| extend Duration = toint(customMeasurements[\"Duration\"])\r\n| summarize Duration=avg(Duration) by bin(timestamp, $__interval)\r\n| order by timestamp asc",
      "resource": "[parameter(product-construction-service-appinsights-resourcepath)]",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "database": "engineeringdata",
     "subscription": "[parameter(dotnet-eng-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "PCS Disk Space Issues",
   "type": "timeseries",
   "description": "Exceptions around disk space running out",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "exceptions\r\n| where timestamp > now()-6h and (outerMessage contains \"No space left on device\" or innermostMessage contains \"No space left on device\")\r\n| summarize TotalCount=count() by bin(timestamp, 1h)\r\n| order by timestamp asc",
      "resource": "[parameter(product-construction-service-appinsights-resourcepath)]"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "[parameter(dotnet-product-construction-services-subscriptionid)]"
    }
   ]
  },
  {
   "title": "Git Push success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customEvents\r\n| where name == \"GitPush\" and $__timeFilter(timestamp)\r\n| extend Success = tobool(customDimensions[\"Success\"])\r\n| summarize SuccessRate=100*countif(Success == true)/count() by bin(timestamp, $__interval)\r\n| order by timestamp asc",
      "resource": "[parameter(product-construction-service-appinsights-resourcepath)]"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "[parameter(dotnet-product-construction-services-subscriptionid)]"
    }
   ]
  },
  {
   "title": "PCS Feed Cleaner",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "traces\r\n| where $__timeFilter(timestamp) and cloud_RoleInstance startswith \"feed-cleaner-prod\" and message has \"cleaning finished\"\r\n| project\r\n    timestamp,\r\n    packagesCleaned = toint(customDimensions[\"count\"]),\r\n    packagesTotal = toint(customDimensions[\"totalCount\"])\r\n| summarize PackagesCleaned=sum(packagesCleaned), PackagesTotal=sum(packagesTotal) by bin(timestamp, 24h)\r\n| order by timestamp asc",
      "resource": "[parameter(product-construction-service-appinsights-resourcepath)]",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "database": "engineeringdata",
     "subscription": "[parameter(dotnet-eng-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "Container jobs with failed latest executions",
   "type": "timeseries",
   "description": "Shows container that failed their latest execution",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "ContainerAppSystemLogs_CL\r\n| where TimeGenerated > ago(14d)\r\n| where Log_s has_any (\"has exited with status Succeeded\", \"has exited with status Failed\")\r\n| summarize arg_max(TimeGenerated, Log_s) by JobName_s\r\n| where Log_s has \"has exited with status Failed\"\r\n| project TimeGenerated,JobName=JobName_s, FailedJob=1",
      "resource": "[parameter(product-construction-service-workspace-resourcepath)]"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.OperationalInsights/workspaces",
      "metricNamespace": "Microsoft.OperationalInsights/workspaces",
      "resourceGroup": "[parameter(product-construction-service-resourcegroup)]",
      "resourceName": "[parameter(product-construction-service-workspace-resourcename)]",
      "timeGrain": "auto"
     },
     "database": "engineeringdata",
     "subscription": "[parameter(dotnet-product-construction-services-subscriptionid)]"
    }
   ]
  },
  {
   "title": "Helix",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "type": "alertlist",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 50 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "azureResourceGraph": { "resultFormat": "table" },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
       "subscriptions": [
        "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
        "cab65fc3-d077-467d-931f-3932eabf36d3"
       ]
      }
     ]
    },
    {
     "title": "Helix API",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 50 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "aggOptions": [],
        "aggregation": "Average",
        "alias": "{{ availabilityresult/location }}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "dimension": "availabilityResult/name", "filter": "Helix API", "operator": "eq" },
         { "dimension": "availabilityResult/location", "filter": "", "operator": "eq" }
        ],
        "metricDefinition": "microsoft.insights/components",
        "metricName": "availabilityResults/availabilityPercentage",
        "metricNamespace": "microsoft.insights/components",
        "resourceGroup": "helixinfrarg",
        "resourceName": "helix-prod",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "azureResourceGraph": { "resultFormat": "table" },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
       "subscriptions": [
        "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
        "cab65fc3-d077-467d-931f-3932eabf36d3"
       ]
      }
     ]
    },
    {
     "title": "Helix Average Response Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 50 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "aggOptions": [],
        "aggregation": "Average",
        "alias": "",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "Microsoft.Insights/components",
        "metricName": "requests/duration",
        "metricNamespace": "microsoft.insights/components",
        "resourceGroup": "dotnet-eng-cluster",
        "resourceName": "dotnet-eng",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "azureResourceGraph": { "resultFormat": "table" },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
       "subscriptions": [
        "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
        "cab65fc3-d077-467d-931f-3932eabf36d3"
       ]
      }
     ]
    },
    {
     "title": "Helix AutoScaler Service Traces",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 16, "x": 0, "y": 59 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "aggOptions": [],
        "aggregation": "Count",
        "alias": "{{cloud/RoleName}}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         {
          "dimension": "cloud/roleName",
          "filter": "fabric:/Helix/AutoScaleActorService",
          "operator": "eq"
         }
        ],
        "metricDefinition": "Microsoft.Insights/components",
        "metricName": "traces/count",
        "metricNamespace": "microsoft.insights/components",
        "resourceGroup": "dotnet-eng-cluster",
        "resourceName": "dotnet-eng",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "100"
       },
       "azureResourceGraph": { "resultFormat": "table" },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
       "subscriptions": [
        "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
        "cab65fc3-d077-467d-931f-3932eabf36d3"
       ]
      }
     ]
    },
    {
     "title": "Helix Failed Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 59 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "aggOptions": [],
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "microsoft.insights/components",
        "metricName": "exceptions/server",
        "metricNamespace": "microsoft.insights/components",
        "resourceGroup": "helixinfrarg",
        "resourceName": "helix-prod",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "azureResourceGraph": { "resultFormat": "table" },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
       "subscriptions": [
        "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
        "cab65fc3-d077-467d-931f-3932eabf36d3"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "DotNetEng Status Failed Requests/Hour",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 51 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "let r = requests | where $__timeFilter(timestamp);\nlet f = coalesce(toscalar(r | summarize min(timestamp)), ago(1d));\nlet t = coalesce(toscalar(r | summarize max(timestamp)), now());\nlet span=(t - f)/60;\nlet interval=case(span >= 1d, bin(span, 1d), span >= 1h, bin(span, 1h), 15m);\nlet intervalHours = interval / 1h;\nr\n| where success == false\n| make-series kind=nonempty valueCount=count() default=0 on timestamp in range(f, t, interval)\n| mv-expand timestamp to typeof(datetime), valueCount to typeof(double)\n| project timestamp, failuresCount=valueCount/intervalHours",
        "resource": "/subscriptions/68672ab8-de0c-40f1-8d1b-ffb20bd62c0f/resourceGroups/monitoring/providers/microsoft.insights/components/DotNetEng-Status-Prod",
        "resultFormat": "time_series",
        "workspace": "/subscriptions/68672ab8-de0c-40f1-8d1b-ffb20bd62c0f/resourcegroups/defaultresourcegroup-eus/providers/microsoft.operationalinsights/workspaces/defaultworkspace-68672ab8-de0c-40f1-8d1b-ffb20bd62c0f-eus"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "azureResourceGraph": { "resultFormat": "table" },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
       "subscriptions": [
        "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
        "cab65fc3-d077-467d-931f-3932eabf36d3"
       ]
      }
     ]
    }
   ]
  }
 ]
}