trigger: none

schedules:
- cron: 0 12 * * *
  displayName: Nightly build
  branches:
    include:
    - main
  always: true

name: $(Date:yyyMMdd)$(Rev:rr)

stages:
  - stage: SynchronizeSecrets
    jobs:
    - job: Synchronize
      pool: 
        name: NetCore1ESPool-Internal-NoMSI
        demands: ImageOverride -equals 1es-windows-2022
      steps:
      - task: UseDotNet@2
        displayName: Install Correct .NET Version
        inputs:
          useGlobalJson: true

      - task: AzureCLI@2
        inputs:
          azureSubscription: DotNet Eng Services Secret Manager
          scriptType: ps
          scriptLocation: inlineScript
          inlineScript: |
            Get-ChildItem .vault-config/*.yaml |% { dotnet run --project src/SecretManager/Microsoft.DncEng.SecretManager -- synchronize --skip-untracked $_}
    
    - job: UploadMarkdownFiles
      pool:
        name: NetCore1ESPool-Internal-NoMSI
        demands: ImageOverride -equals 1es-windows-2022
      steps:
      - checkout: git://internal/dotnet-arcade
      - checkout: git://internal/dotnet-dnceng/src/Chatbot/UploadDocs@dev/internship

      - task: AzureCLI@2
        displayName: 'Run UploadDocs Console App'
        inputs:
          azureSubscription: 'dnceng-internaltooling'
          scriptType: ps
          scriptLocation: 'inlineScript'
          inlineScript: >
            dotnet build $(Pipeline.Workspace)/Binaries/UploadDocs/UploadDocs.csproj -c Release
            dotnet $(Pipeline.Workspace)/Binaries/UploadDocs/Release/net6.0/publish/UploadDocs.dll