{
 "title": "Home",
 "time": { "from": "now-4M", "to": "now" },
 "panels": [
  {
   "title": "Introduction",
   "type": "text",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "options": {
    "content": "\n# .NET Engineering Systems Monitoring\n\nFor questions or permission issues, email [dnceng@microsoft.com](mailto:dnceng@microsoft.com)\n\nThis monitoring site is used to monitor all services managed by the .NET Engineering team.\nFor information about what sorts of things are monitored, and how to go about adding new monitoring or alerting, see the [Guidance](https://github.com/dotnet/core-eng/blob/master/Documentation/Alerting.md).\n\nTo see information about privacy and cookies visit: [Microsoft Privacy Statement](https://go.microsoft.com/fwlink/?LinkId=521839).\n\n"
   }
  },
  { "title": "dnceng", "type": "dashlist", "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 } },
  { "title": "helix-services", "type": "dashlist", "gridPos": { "h": 7, "w": 7, "x": 17, "y": 6 } },
  {
   "title": "Work Items Waiting Time (Build Pools)",
   "type": "table",
   "description": "Screen-reader navigable table of Build Pool work item waiting times in minutes per day. It presents the 95th percentile (Percentile95) and median (Percentile50). Values above the 30 minute threshold are considered too high.",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "database": "engineeringdata",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "WorkItems \n| where  $__timeFilter(Queued)\n| project QueueName = tolower(QueueName), duration = datetime_diff('second', Started, Queued), Queued\n| where QueueName !contains \"osx\" and QueueName !contains \"perf\" and QueueName !contains \"arm\" and QueueName !contains \"arcade\" and QueueName !contains \"xaml\" and QueueName !contains \"appcompat\"\n| where QueueName contains \"buildpool\"\n| summarize Percentile95 = percentile(duration, 95) / 60 by bin(Queued, 1d)\n| order by Queued asc ",
     "querySource": "raw"
    },
    {
     "database": "engineeringdata",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "WorkItems \n| where  $__timeFilter(Queued)\n| project QueueName = tolower(QueueName), duration = datetime_diff('second', Started, Queued), Queued\n| where QueueName !contains \"osx\" and QueueName !contains \"perf\" and QueueName !contains \"arm\" and QueueName !contains \"arcade\" and QueueName !contains \"xaml\" and QueueName !contains \"appcompat\"\n| where QueueName contains \"buildpool\"\n| summarize Percentile50 = percentile(duration, 50) / 60 by bin(Queued, 1d)\n| order by Queued asc ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Work Items Waiting Time (Test Queues)",
   "type": "table",
   "description": "Screen-reader navigable table of Test Queue work item waiting times in minutes per day. It presents the 95th percentile (Percentile95) and median (Percentile50). Values above the 35 minute threshold are considered too high.",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "database": "engineeringdata",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "WorkItems \n| where  $__timeFilter(Queued)\n| project QueueName = tolower(QueueName), duration = datetime_diff('second', Started, Queued), Queued\n| where QueueName !contains \"osx\" and QueueName !contains \"perf\" and QueueName !contains \"arm\" and QueueName !contains \"arcade\" and QueueName !contains \"xaml\" and QueueName !contains \"appcompat\" and QueueName !contains \".tof\"\n| where QueueName !contains \"buildpool\"\n| summarize Percentile95 = percentile(duration, 95) / 60 by bin(Queued, 1d)\n| order by Queued asc ",
     "querySource": "raw"
    },
    {
     "database": "engineeringdata",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "WorkItems \n| where  $__timeFilter(Queued)\n| project QueueName = tolower(QueueName), duration = datetime_diff('second', Started, Queued), Queued\n| where QueueName !contains \"osx\" and QueueName !contains \"perf\" and QueueName !contains \"arm\" and QueueName !contains \"arcade\" and QueueName !contains \"xaml\" and QueueName !contains \"appcompat\"\n| where QueueName !contains \"buildpool\"\n| summarize Percentile50 = percentile(duration, 50) / 60 by bin(Queued, 1d)\n| order by Queued asc ",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Currently Active Alerts", "type": "alertlist", "gridPos": { "h": 13, "w": 7, "x": 17, "y": 13 } },
  {
   "title": "Number of Crashes in Helix",
   "type": "timeseries",
   "description": "This panel shows all the times the Helix client crashed while processing a work item.  The goal for this is to be greater than 99.99% reliability.",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "database": "engineeringdata",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "WorkItems\n| where Finished > ago(120d)\n| extend my=startofmonth(Finished)\n| summarize Pass=countif(Status != \"None\"), Fail=countif(Status == \"None\") by my\n| project my, PassPercent = toreal(Pass) / toreal(Pass + Fail)\n| order by my desc \n| limit 4\n| order by my asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Work Items Waiting Time (Build Pools) - Accessible Data Table",
   "type": "table",
   "description": "Accessible data table equivalent of the \"Work Items Waiting Time (Build Pools)\" time series graph. Presents the same data as a screen-reader navigable table (MAS 1.3.1 - Info and Relationships): the 95th percentile (Percentile95) and median 50th percentile (Percentile50) of Build Pool work item waiting times, in minutes, per day. Values above the 30 minute threshold are considered too high.",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "database": "engineeringdata",
     "query": "WorkItems \n| where  $__timeFilter(Queued)\n| project QueueName = tolower(QueueName), duration = datetime_diff('second', Started, Queued), Queued\n| where QueueName !contains \"osx\" and QueueName !contains \"perf\" and QueueName !contains \"arm\" and QueueName !contains \"arcade\" and QueueName !contains \"xaml\" and QueueName !contains \"appcompat\"\n| where QueueName contains \"buildpool\"\n| summarize Percentile95 = percentile(duration, 95) / 60 by bin(Queued, 1d)\n| order by Queued asc ",
     "querySource": "raw"
    },
    {
     "database": "engineeringdata",
     "query": "WorkItems \n| where  $__timeFilter(Queued)\n| project QueueName = tolower(QueueName), duration = datetime_diff('second', Started, Queued), Queued\n| where QueueName !contains \"osx\" and QueueName !contains \"perf\" and QueueName !contains \"arm\" and QueueName !contains \"arcade\" and QueueName !contains \"xaml\" and QueueName !contains \"appcompat\"\n| where QueueName contains \"buildpool\"\n| summarize Percentile50 = percentile(duration, 50) / 60 by bin(Queued, 1d)\n| order by Queued asc ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Work Items Waiting Time (Test Queues) - Accessible Data Table",
   "type": "table",
   "description": "Accessible data table equivalent of the \"Work Items Waiting Time (Test Queues)\" time series graph. Presents the same data as a screen-reader navigable table (MAS 1.3.1 - Info and Relationships): the 95th percentile (Percentile95) and median 50th percentile (Percentile50) of Test Queue work item waiting times, in minutes, per day. Values above the 35 minute threshold are considered too high.",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "database": "engineeringdata",
     "query": "WorkItems \n| where  $__timeFilter(Queued)\n| project QueueName = tolower(QueueName), duration = datetime_diff('second', Started, Queued), Queued\n| where QueueName !contains \"osx\" and QueueName !contains \"perf\" and QueueName !contains \"arm\" and QueueName !contains \"arcade\" and QueueName !contains \"xaml\" and QueueName !contains \"appcompat\" and QueueName !contains \".tof\"\n| where QueueName !contains \"buildpool\"\n| summarize Percentile95 = percentile(duration, 95) / 60 by bin(Queued, 1d)\n| order by Queued asc ",
     "querySource": "raw"
    },
    {
     "database": "engineeringdata",
     "query": "WorkItems \n| where  $__timeFilter(Queued)\n| project QueueName = tolower(QueueName), duration = datetime_diff('second', Started, Queued), Queued\n| where QueueName !contains \"osx\" and QueueName !contains \"perf\" and QueueName !contains \"arm\" and QueueName !contains \"arcade\" and QueueName !contains \"xaml\" and QueueName !contains \"appcompat\"\n| where QueueName !contains \"buildpool\"\n| summarize Percentile50 = percentile(duration, 50) / 60 by bin(Queued, 1d)\n| order by Queued asc ",
     "querySource": "raw"
    }
   ]
  }
 ]
}