trigger:
- "t-jelipscomb/AIChatbotDataPipeline"

pool:
  vmImage: 'windows-latest'

jobs:
  - job: build
    timeoutInMinutes: 360
    steps:
    - checkout: self
      path: dnceng
    - checkout: git://internal/dotnet-arcade
      path: arcade
   # - task: UseDotNet@2
   #   inputs:
   #     useGlobalJson: true
   #   displayName: Install default .NET SDK
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          choco install pandoc --yes
      displayName: 'Install Pandoc using Chocolatey'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          choco install miktex --yes --verbose
          choco install rsvg-convert --yes --verbose
          write-host $env:PATH
          $env:Path += ";C:\Program Files\MiKTeX\miktex\bin\x64"
          mpm --update --list --admin
          mpm --update --list 
          write-host $env:PATH
      displayName: 'Install MikTex and xetex using Chocolatey'
    - script: |
        pwd
        ls
      displayName: Print working directory
    
    #- task: PowerShell@2
    #  inputs:
    #    targetType: 'filePath'
    #    filePath: 'src\AIChatbot\scripts\PublishDocumentationIndex.ps1'
    #  displayName: 'Run PublishDocumentationIndex.ps1 script to prepare and push docs'
    
    - task: AzureCLI@2
      displayName: 'Run PublishDocumentationIndex.ps1 script to prepare and push docs'
      inputs:
        azureSubscription: dd8c2cfc-b9c9-452c-a168-ccd4240ada55
        scriptType: pscore
        scriptLocation: scriptPath
        scriptPath: 'dnceng\eng\PublishDocumentationIndex.ps1'
      