parameters:
- name: ServiceConnectionName
  type: string
- name: ServiceConnectionId
  type: string
- name: DeploymentEnvironment
  type: string
- name: GrafanaWorkspaceName
  type: string
- name: EnableCustomDomain
  type: boolean
  default: true

stages:
- stage: ProvisionGrafana
  displayName: 'Provision Grafana Infrastructure'
  # dependsOn:
  # - predeploy
  # - approval
  jobs:
  - template: /eng/provision-grafana.yaml@self
    parameters:
      DeploymentEnvironment: ${{ parameters.DeploymentEnvironment }}
      ServiceConnectionName: ${{ parameters.ServiceConnectionName }}
      GrafanaResourceGroup: 'monitoring-managed'
      GrafanaWorkspaceName: ${{ parameters.GrafanaWorkspaceName }}
      GrafanaLocation: 'westus2'

- stage: ProvisionApplicationGateway
  displayName: 'Provision Application Gateway Custom Domain'
  dependsOn: ProvisionGrafana
  condition: and(succeeded(), eq(${{ parameters.EnableCustomDomain }}, true))
  jobs:
  - job: DeployApplicationGateway
    displayName: 'Deploy Azure Application Gateway'
    pool:
      name: NetCore1ESPool-Internal
      demands: ImageOverride -equals 1es-windows-2022
    steps:
    - template: /eng/provision-appgw.yaml@self
      parameters:
        SubscriptionId: ${{ parameters.ServiceConnectionId }}
        ServiceConnection: ${{ parameters.ServiceConnectionName }}
        ResourceGroupName: 'monitoring-managed'
        Environment: ${{ parameters.DeploymentEnvironment }}
        GrafanaWorkspaceName: ${{ parameters.GrafanaWorkspaceName }}
        Location: 'westus2'
