parameters:
  Subscription: ''
  PublishProfile: ''
  DotNetStatusAppName: ''
  DeploymentEnvironment: ''
  DotNetStatusEndpoint: ''
  StatusVariableGroup: ''

  # --- Secret Variable group requirements ---
  # dotnet-build-bot-dotnet-eng-status-token
  # secret-manager-scenario-tests-client-secret

stages:
- stage: validateDeployment
  displayName: Validate deployment
  pool:
    name: NetCore1ESPool-Internal
    demands: ImageOverride -equals 1es-windows-2019
  variables:
  # Secret-Manager-Scenario-Tests provides: 
  #   - secret-manager-scenario-tests-app-id
  #   - secret-manager-scenario-tests-app-secret
  - group: Secret-Manager-Scenario-Tests
  jobs:
  - job: scenario
    displayName: Scenario tests
    timeoutInMinutes: 90
    steps:
    - download: current
      artifact: PackageArtifacts
    - download: current
      artifact: Microsoft.DncEng.SecretManager.ScenarioTests

    - task: NuGetToolInstaller@1
      displayName: Use NuGet
      inputs:
        versionSpec: 5.3.x

    - task: UseDotNet@2
      displayName: Install Correct .NET Version
      inputs:
        useGlobalJson: true

    - task: AzureCLI@2
      displayName: Secret Manager Scenario Tests (in AzureCLI)
      inputs: 
        azureSubscription: DotNet Eng Services Secret Manager
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          dotnet test $(System.DefaultWorkingDirectory)/src/SecretManager/Microsoft.DncEng.SecretManager.ScenarioTests/Microsoft.DncEng.SecretManager.ScenarioTests.csproj

    - task: VSTest@2
      displayName: Secret Manager Scenario Tests
      inputs:
        testSelector: testAssemblies
        testAssemblyVer2: |
          Microsoft.DncEng.SecretManager.ScenarioTests.dll
        searchFolder: $(Pipeline.Workspace)/Microsoft.DncEng.SecretManager.ScenarioTests
      env:
        AZURE_TENANT_ID: 72f988bf-86f1-41af-91ab-2d7cd011db47
        AZURE_CLIENT_ID: $(secret-manager-scenario-tests-app-id)
        AZURE_CLIENT_SECRET: $(secret-manager-scenario-tests-app-secret)