parameters:
- name: ServiceConnectionName
  type: string
- name: ServiceConnectionId
  type: string
- name: DeploymentEnvironment
  type: string
- name: GrafanaWorkspaceName
  type: string

stages:
- stage: ProvisionGrafana
  displayName: 'Provision Grafana Infrastructure'
  # dependsOn:
  # - predeploy
  # - approval
  jobs:
  - template: /eng/provision-grafana.yaml@self
    parameters:
      DeploymentEnvironment: ${{ parameters.DeploymentEnvironment }}
      ServiceConnectionName: ${{ parameters.ServiceConnectionName }}
      GrafanaResourceGroup: 'monitoring-managed'
      GrafanaWorkspaceName: ${{ parameters.GrafanaWorkspaceName }}
      GrafanaLocation: 'westus2'
