parameters:
  Subscription: ''
  PublishProfile: ''
  DotNetStatusAppName: ''
  DeploymentEnvironment: ''
  DotNetStatusEndpoint: ''
  StatusVariableGroup: ''

  # --- Secret Variable group requirements ---
  # dotnet-build-bot-dotnet-eng-status-token
  # secret-manager-scenario-tests-client-secret

stages:
- stage: validateDeployment
  dependsOn:
  - build
  displayName: Validate deployment
  pool:
    name: NetCore1ESPool-Internal
    demands: ImageOverride -equals 1es-windows-2019
  variables:
  # Secret-Manager-Scenario-Tests provides: 
  #   - secret-manager-scenario-tests-app-id
  #   - secret-manager-scenario-tests-app-secret
  - group: Secret-Manager-Scenario-Tests
  jobs:
  - job: scenario
    displayName: Scenario tests
    timeoutInMinutes: 90
    steps:
    - download: current
      artifact: PackageArtifacts
    - download: current
      artifact: Microsoft.DncEng.SecretManager.ScenarioTests

    - task: NuGetToolInstaller@1
      displayName: Use NuGet
      inputs:
        versionSpec: 5.3.x

    - task: UseDotNet@2
      displayName: Install Correct .NET Version
      inputs:
        useGlobalJson: true

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'secret-manager-scenario-tests'
        addSpnToEnvironment: true
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$env:servicePrincipalId" 
          echo "##vso[task.setvariable variable=ARM_ID_TOKEN]$env:idToken"
          echo "##vso[task.setvariable variable=ARM_TENANT_ID]$env:tenantId"
  
    - script: |
        echo "Client ID: $(ARM_CLIENT_ID)"
        echo "ID Token: $(ARM_ID_TOKEN)"
        echo "Tenant ID: $(ARM_TENANT_ID)"
        az login --service-principal -u $(ARM_CLIENT_ID) --tenant $(ARM_TENANT_ID) --allow-no-subscriptions --federated-token $(ARM_ID_TOKEN)
      displayName: "Login to Azure"

    - task: VSTest@2
      displayName: Secret Manager Scenario Tests
      inputs:
        testSelector: testAssemblies
        testAssemblyVer2: |
          Microsoft.DncEng.SecretManager.ScenarioTests.dll
        searchFolder: $(Pipeline.Workspace)/Microsoft.DncEng.SecretManager.ScenarioTests