parameters:
- name: ServiceConnectionName
  type: string
- name: ServiceConnectionClientId
  type: string
- name: ServiceConnectionId
  type: string
- name: PublishProfile
  type: string
- name: DotNetStatusAppName
  type: string
- name: DeploymentEnvironment
  type: string
- name: DotNetStatusEndpoint
  type: string
- name: StatusVariableGroup
  type: string
- name: RolloutScorerAppName
  type: string
- name: GrafanaHost
  type: string
- name: GrafanaKeyVault
  type: string
- name: GrafanaVariableGroup
  type: string

  # --- Secret Variable group requirements ---
  # dotnet-build-bot-dotnet-eng-status-token

stages:
- stage: ValidateSecrets
  dependsOn:
  - build
  jobs:
  - job: ValidateSecrets
    pool: 
      name: NetCore1ESPool-Internal-NoMSI
      demands: ImageOverride -equals 1es-windows-2022
    steps:
    - task: UseDotNet@2
      displayName: Install .NET from global.json
      inputs:
        useGlobalJson: true
        
    - task: UseDotNet@2
      displayName: Install .NET 6
      inputs:
        version: 6.x

    - task: AzureCLI@2
      displayName: Synchronize Secrets
      inputs:
        azureSubscription: DotNet Eng Services Secret Manager
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          Get-ChildItem .vault-config/*.yaml |% { dotnet run --project src/SecretManager/Microsoft.DncEng.SecretManager -- synchronize --verify-only $_}

- stage: approval
  pool: server
  dependsOn:
  - build
  - Validate
  - ValidateSecrets
  - publish_using_darc
  jobs:
  - deployment: approval
    displayName: deployment approval (conditional)
    environment: ${{ parameters.DeploymentEnvironment }}

- stage: predeploy
  displayName: Pre-Deployment
  pool: server
  dependsOn:
  - build
  - Validate
  - approval
  jobs:
  - job: notifyStartDeployment
    displayName: Notify deployment start
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      displayName: Notify dotnet-eng-status/start
      continueOnError: true
      inputs:
        serviceConnection: ${{ parameters.DotNetStatusEndpoint }}
        method: POST
        urlSuffix: /dnceng/$(Build.BuildNumber)/start

- stage: deploy
  displayName: Deploy
  pool:
    name: NetCore1ESPool-Internal-NoMSI
    demands: ImageOverride -equals 1es-windows-2019
  dependsOn:
  - predeploy
  - approval
  variables:
  - name: PublishProfile
    value: ${{ parameters.PublishProfile }}
  jobs:
  - job: deployTelemetry
    displayName: Deploy telemetry service fabric application
    pool:
      name: NetCore1ESPool-Internal-NoMSI
      demands: ImageOverride -equals 1es-windows-2019
    steps:
    - download: current
      artifact: TelemetryApplication
    - download: current
      artifact: ReleaseUtilities
    - task: AzurePowerShell@5
      displayName: Deploy Service Fabric Application (Telemetry)
      inputs:
        azureSubscription: ${{ parameters.ServiceConnectionName }}
        scriptType: inlineScript
        azurePowerShellVersion: LatestVersion
        inline: |
          $autoRollBack = $true
          if ($env:DisableAutoRollBack -eq 'true') {
            $autoRollBack = $false
          }
          if ($env:BUILD_SOURCEBRANCH -eq 'refs/heads/main') {
            $autoRollBack = $false
          }
          eng/deployment/deploy.ps1 -obj $env:BUILD_ARTIFACTSTAGINGDIRECTORY -appPackagePath $env:ApplicationPackage -publishProfile $env:PublishProfilePath -autoRollBack $autoRollBack -location westus2
      env:
        PublishProfilePath: $(Pipeline.Workspace)/TelemetryApplication/projectartifacts/PublishProfiles/$(PublishProfile).xml
        ApplicationPackage: $(Pipeline.Workspace)/TelemetryApplication/applicationpackage

  - job: deployStatus
    displayName: Deploy dotnet-status web app
    pool:
      name: NetCore1ESPool-Internal-NoMSI
      demands: ImageOverride -equals 1es-windows-2019
    steps:
    - download: current
      artifact: DotNetStatus
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: AzureRM
        azureSubscription: ${{ parameters.ServiceConnectionName }}
        appType: webApp
        WebAppName: ${{ parameters.DotNetStatusAppName }}
        deployToSlotOrASE: true
        ResourceGroupName: monitoring
        SlotName: staging
        Package: $(Pipeline.Workspace)/DotNetStatus/DotNetStatus.zip
        enableCustomDeployment: true
        DeploymentType: zipDeploy
        RemoveAdditionalFilesFlag: true

  - job: deployRolloutScorer
    displayName: Deploy rollout scorer azure function
    pool:
      name: NetCore1ESPool-Internal-NoMSI
      demands: ImageOverride -equals 1es-windows-2019
    steps:
    - download: current
      artifact: RolloutScorer
    - task: AzureFunctionApp@1
      displayName: Deploy RolloutScorer
      inputs:
        azureSubscription: ${{ parameters.ServiceConnectionName }}
        ${{ if ne(parameters.DeploymentEnvironment, 'Production') }}:
          appSettings: >
            -DeploymentEnvironment Staging
            -ScorecardsStorageAccountKeySecretName "rolloutscorecardsstaging-storage-key"
            -ScorecardsStorageAccountName "rolloutscorecardsstaging"
            -ScorecardsStorageAccountTableName "scorecardsstaging"
        ${{ if eq(parameters.DeploymentEnvironment, 'Production') }}:
          appSettings: >
            -DeploymentEnvironment Production
            -ScorecardsStorageAccountKeySecretName "rolloutscorecards-storage-key"
            -ScorecardsStorageAccountName "rolloutscorecards"
            -ScorecardsStorageAccountTableName "scorecards"
        package: $(Pipeline.Workspace)/RolloutScorer/RolloutScorer.zip
        appName: ${{ parameters.RolloutScorerAppName }}

- stage: postdeploy
  displayName: Post-Deployment
  pool:
    name: NetCore1ESPool-Internal-NoMSI
    demands: ImageOverride -equals 1es-windows-2019
  dependsOn:
  - deploy
  variables:
  - group: ${{ parameters.StatusVariableGroup }}
  - group: ${{ parameters.GrafanaVariableGroup }}
  - name: DeploymentEnvironment
    value: ${{ parameters.DeploymentEnvironment }}
  - name: GrafanaHost
    value: ${{ parameters.GrafanaHost }}
  - name: GrafanaKeyVault
    value: ${{ parameters.GrafanaKeyVault }}
  - name: GrafanaClientId
    value: ${{ parameters.ServiceConnectionClientId }}
  - name: GrafanaServiceConnectionId
    value: ${{ parameters.ServiceConnectionId }}
  jobs:
  - job: notifyEndDeployment
    displayName: Notify deployment end
    condition: always()
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      displayName: Notify dotnet-eng-status/end
      continueOnError: true
      inputs:
        serviceConnection: ${{ parameters.DotNetStatusEndpoint }}
        method: POST
        urlSuffix: /dnceng/$(Build.BuildNumber)/end
  - job: updateMetrics
    displayName: Update Grafana Metrics
    steps:
    - task: UseDotNet@2
      displayName: Install Correct .NET Version
      inputs:
        useGlobalJson: true
    - script: dotnet publish $(Build.SourcesDirectory)\src\Monitoring\Sdk\Microsoft.DotNet.Monitoring.Sdk.csproj -f net6.0
      displayName: Build Monitoring SDK
    - script: dotnet build $(Build.SourcesDirectory)\src\Monitoring\Monitoring.ArcadeServices\Monitoring.ArcadeServices.proj -t:PublishGrafana -p:GrafanaAccessToken=$(grafana-admin-api-key) -p:GrafanaHost=$(GrafanaHost) -p:GrafanaKeyVaultName=$(GrafanaKeyVault) -p:ClientId=$(GrafanaClientId) -p:ServiceConnectionId=$(GrafanaServiceConnectionId) -p:SystemAccessToken=$(System.AccessToken) -p:GrafanaEnvironment=$(DeploymentEnvironment) -p:ParametersFile=parameters.json -v:normal
      displayName: Publish Grafana Dashboards

- stage: validateDeployment
  displayName: Validate deployment
  pool:
    name: NetCore1ESPool-Internal
    demands: ImageOverride -equals 1es-windows-2019
  dependsOn:
  - deploy
  jobs:
  - job: scenario
    displayName: Scenario tests
    timeoutInMinutes: 90
    steps:
    - download: current
      artifact: PackageArtifacts
    - download: current
      artifact: Microsoft.DncEng.SecretManager.ScenarioTests

    - task: NuGetToolInstaller@1
      displayName: Use NuGet
      inputs:
        versionSpec: 5.3.x

    - task: UseDotNet@2
      displayName: Install .NET 6
      inputs:
        version: 6.x

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'secret-manager-scenario-tests'
        addSpnToEnvironment: true
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "##vso[task.setvariable variable=ARM_CLIENT_ID;isSecret=true]$env:servicePrincipalId" 
          echo "##vso[task.setvariable variable=ARM_TENANT_ID;isSecret=true]$env:tenantId"
          echo "##vso[task.setvariable variable=ARM_ID_TOKEN;isSecret=true]$env:idToken"
  
    - script: |
        az login --service-principal -u $(ARM_CLIENT_ID) --tenant $(ARM_TENANT_ID) --allow-no-subscriptions --federated-token $(ARM_ID_TOKEN)
      displayName: "Login to Azure"

    - task: VSTest@2
      displayName: Secret Manager Scenario Tests
      inputs:
        testSelector: testAssemblies
        testAssemblyVer2: |
          Microsoft.DncEng.SecretManager.ScenarioTests.dll
        searchFolder: $(Pipeline.Workspace)/Microsoft.DncEng.SecretManager.ScenarioTests