parameters:
- name: ServiceConnectionName
  type: string
- name: ServiceConnectionClientId
  type: string
- name: ServiceConnectionId
  type: string
- name: DeploymentEnvironment
  type: string
- name: GrafanaWorkspaceName
  type: string
- name: GrafanaKeyVault
  type: string
- name: GrafanaVariableGroup
  type: string
- name: DotnetEngServicesGroupObjectId
  type: string
  default: "65d7fc1d-2744-4669-8779-5cd7d7a6b95b"


stages:
- stage: ProvisionGrafana
  displayName: 'Provision Grafana Infrastructure'
  jobs:
  - template: /eng/provision-grafana.yaml@self
    parameters:
      DeploymentEnvironment: ${{ parameters.DeploymentEnvironment }}
      ServiceConnectionName: ${{ parameters.ServiceConnectionName }}
      GrafanaResourceGroup: 'monitoring-managed'
      GrafanaWorkspaceName: ${{ parameters.GrafanaWorkspaceName }}
      GrafanaLocation: 'westus2'
      GrafanaKeyVault: ${{ parameters.GrafanaKeyVault }}
      GrafanaVariableGroup: ${{ parameters.GrafanaVariableGroup }}
      DotnetEngServicesGroupObjectId: ${{ parameters.DotnetEngServicesGroupObjectId }}