parameters:
- name: ServiceConnectionName
  type: string
- name: ServiceConnectionClientId
  type: string
- name: ServiceConnectionId
  type: string
- name: PublishProfile
  type: string
- name: DotNetStatusAppName
  type: string
- name: DeploymentEnvironment
  type: string
- name: DotNetStatusEndpoint
  type: string
- name: StatusVariableGroup
  type: string
- name: AMGServiceConnectionName
  type: string
- name: AMGServiceConnectionClientId
  type: string
- name: AMGServiceConnectionId
  type: string
- name: AMGDeploymentEnvironment
  type: string
- name: AMGGrafanaWorkspaceName
  type: string
- name: AMGGrafanaKeyVault
  type: string

  # --- Secret Variable group requirements ---
  # dotnet-build-bot-dotnet-eng-status-token

stages:
- stage: ValidateSecrets
  dependsOn:
  - build
  jobs:
  - job: ValidateSecrets
    pool: 
      name: NetCore1ESPool-Internal-NoMSI
      demands: ImageOverride -equals 1es-windows-2022
    steps:
    - task: UseDotNet@2
      displayName: Install .NET from global.json
      inputs:
        useGlobalJson: true
        
    - task: UseDotNet@2
      displayName: Install .NET 6
      inputs:
        version: 6.x

    - task: AzureCLI@2
      displayName: Synchronize Secrets
      inputs:
        azureSubscription: DotNet Eng Services Secret Manager
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          Get-ChildItem .vault-config/*.yaml |% { dotnet run --project src/SecretManager/Microsoft.DncEng.SecretManager -- synchronize --verify-only $_}

- stage: approval
  pool: server
  dependsOn:
  - build
  - Validate
  - ValidateSecrets
  - publish_using_darc
  jobs:
  - deployment: approval
    displayName: deployment approval (conditional)
    environment: ${{ parameters.DeploymentEnvironment }}

- stage: predeploy
  displayName: Pre-Deployment
  pool: server
  dependsOn:
  - build
  - Validate
  - approval
  jobs:
  - job: notifyStartDeployment
    displayName: Notify deployment start
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      displayName: Notify dotnet-eng-status/start
      continueOnError: true
      inputs:
        serviceConnection: ${{ parameters.DotNetStatusEndpoint }}
        method: POST
        urlSuffix: /dnceng/$(Build.BuildNumber)/start

- stage: deploy
  displayName: Deploy
  pool:
    name: NetCore1ESPool-Internal-NoMSI
    demands: ImageOverride -equals 1es-windows-2022
  dependsOn:
  - predeploy
  - approval
  variables:
  - name: PublishProfile
    value: ${{ parameters.PublishProfile }}
  jobs:
  - job: deployTelemetry
    displayName: Deploy telemetry service fabric application
    pool:
      name: NetCore1ESPool-Internal-NoMSI
      demands: ImageOverride -equals 1es-windows-2022
    steps:
    - download: current
      artifact: TelemetryApplication
    - download: current
      artifact: ReleaseUtilities
    - task: AzurePowerShell@5
      displayName: Deploy Service Fabric Application (Telemetry)
      inputs:
        azureSubscription: ${{ parameters.ServiceConnectionName }}
        scriptType: inlineScript
        azurePowerShellVersion: LatestVersion
        inline: |
          $autoRollBack = $true
          if ($env:DisableAutoRollBack -eq 'true') {
            $autoRollBack = $false
          }
          if ($env:BUILD_SOURCEBRANCH -eq 'refs/heads/main') {
            $autoRollBack = $false
          }
          eng/deployment/deploy.ps1 -obj $env:BUILD_ARTIFACTSTAGINGDIRECTORY -appPackagePath $env:ApplicationPackage -publishProfile $env:PublishProfilePath -autoRollBack $autoRollBack -location westus2
      env:
        PublishProfilePath: $(Pipeline.Workspace)/TelemetryApplication/projectartifacts/PublishProfiles/$(PublishProfile).xml
        ApplicationPackage: $(Pipeline.Workspace)/TelemetryApplication/applicationpackage

  - job: deployStatus
    displayName: Deploy dotnet-status web app
    pool:
      name: NetCore1ESPool-Internal-NoMSI
      demands: ImageOverride -equals 1es-windows-2022
    steps:
    - download: current
      artifact: DotNetStatus
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: AzureRM
        azureSubscription: ${{ parameters.ServiceConnectionName }}
        appType: webApp
        WebAppName: ${{ parameters.DotNetStatusAppName }}
        deployToSlotOrASE: true
        ResourceGroupName: monitoring
        SlotName: staging
        Package: $(Pipeline.Workspace)/DotNetStatus/DotNetStatus.zip
        enableCustomDeployment: true
        DeploymentType: zipDeploy
        RemoveAdditionalFilesFlag: true

- template: /eng/deploy-managed-grafana.yml@self
  parameters:
    AMGServiceConnectionName: ${{ parameters.AMGServiceConnectionName }}
    AMGServiceConnectionId: ${{ parameters.AMGServiceConnectionId }}
    AMGServiceConnectionClientId: ${{ parameters.AMGServiceConnectionClientId }}
    AMGDeploymentEnvironment: ${{ parameters.AMGDeploymentEnvironment }}
    AMGGrafanaWorkspaceName: ${{ parameters.AMGGrafanaWorkspaceName }}
    AMGGrafanaKeyVault: ${{ parameters.AMGGrafanaKeyVault }}

- stage: postdeploy
  displayName: Post-Deployment
  pool:
    name: NetCore1ESPool-Internal-NoMSI
    demands: ImageOverride -equals 1es-windows-2022
  dependsOn:
  - deploy
  - DeployGrafana
  variables:
  - group: ${{ parameters.StatusVariableGroup }}
  jobs:
  - job: notifyEndDeployment
    displayName: Notify deployment end
    condition: always()
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      displayName: Notify dotnet-eng-status/end
      continueOnError: true
      inputs:
        serviceConnection: ${{ parameters.DotNetStatusEndpoint }}
        method: POST
        urlSuffix: /dnceng/$(Build.BuildNumber)/end

- stage: validateDeployment
  displayName: Validate deployment
  pool:
    name: NetCore1ESPool-Internal
    demands: ImageOverride -equals 1es-windows-2022
  dependsOn:
  - deploy
  - DeployGrafana
  jobs:
  - job: scenario
    displayName: Scenario tests
    timeoutInMinutes: 90
    steps:
    - download: current
      artifact: PackageArtifacts
    - download: current
      artifact: Microsoft.DncEng.SecretManager.ScenarioTests

    - task: NuGetToolInstaller@1
      displayName: Use NuGet
      inputs:
        versionSpec: 5.3.x

    - task: UseDotNet@2
      displayName: Install .NET 8
      inputs:
        version: 8.x

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'secret-manager-scenario-tests'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          dotnet test $(Pipeline.Workspace)/Microsoft.DncEng.SecretManager.ScenarioTests/Microsoft.DncEng.SecretManager.ScenarioTests.dll
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      displayName: Secret Manager Scenario Tests
