{
 "title": "Service Availability",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "alertlist",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "[parameter(emptystring)]"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "[parameter(dotnet-eng-appinsights-subscriptionid)]",
     "subscriptions": [
      "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
      "cab65fc3-d077-467d-931f-3932eabf36d3"
     ]
    }
   ]
  },
  {
   "title": "Helix API",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "[parameter(emptystring)]"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "alias": "{{ availabilityresult/location }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "availabilityResult/name", "filter": "Helix API", "operator": "eq" },
       { "dimension": "availabilityResult/location", "filter": "", "operator": "eq" }
      ],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "availabilityResults/availabilityPercentage",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "[parameter(helix-client-appinsights-resourcegroup)]",
      "resourceName": "[parameter(helix-appinsights-resourcename)]",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "[parameter(dotnet-eng-appinsights-subscriptionid)]",
     "subscriptions": [
      "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
      "cab65fc3-d077-467d-931f-3932eabf36d3"
     ]
    }
   ]
  },
  {
   "title": "Helix Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "[parameter(emptystring)]"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "requests/duration",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "[parameter(dotnet-eng-appinsights-resourcegroup)]",
      "resourceName": "[parameter(dotnet-eng-appinsights-resourcename)]",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "[parameter(dotnet-eng-appinsights-subscriptionid)]",
     "subscriptions": [
      "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
      "cab65fc3-d077-467d-931f-3932eabf36d3"
     ]
    }
   ]
  },
  {
   "title": "Helix Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "[parameter(emptystring)]"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "exceptions/server",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "[parameter(helix-client-appinsights-resourcegroup)]",
      "resourceName": "[parameter(helix-appinsights-resourcename)]",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "[parameter(dotnet-eng-appinsights-subscriptionid)]",
     "subscriptions": [
      "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
      "cab65fc3-d077-467d-931f-3932eabf36d3"
     ]
    }
   ]
  },
  {
   "title": "Source Browser",
   "type": "timeseries",
   "description": "Availability tests for the site source.dot.net.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "[parameter(emptystring)]"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "availabilityResult/name", "filter": "source-dot-net", "operator": "eq" }
      ],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "availabilityResults/availabilityPercentage",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "[parameter(dotnet-eng-appinsights-resourcegroup)]",
      "resourceName": "[parameter(dotnet-eng-appinsights-resourcename)]",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "[parameter(dotnet-eng-appinsights-subscriptionid)]",
     "subscriptions": [
      "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
      "cab65fc3-d077-467d-931f-3932eabf36d3"
     ]
    }
   ]
  },
  {
   "title": "Maestro / BarViz",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "[parameter(emptystring)]"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "alias": "{{ availabilityresult/location }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "availabilityResult/location", "filter": "", "operator": "eq" }
      ],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "availabilityResults/availabilityPercentage",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "[parameter(maestro-appinsights-resourcegroup)]",
      "resourceName": "[parameter(maestro-appinsights-resourcename)]",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "[parameter(dotnet-eng-appinsights-subscriptionid)]",
     "subscriptions": [
      "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
      "cab65fc3-d077-467d-931f-3932eabf36d3"
     ]
    }
   ]
  },
  {
   "title": "Maestro Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "[parameter(emptystring)]"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "requests/duration",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "[parameter(maestro-appinsights-resourcegroup)]",
      "resourceName": "[parameter(maestro-appinsights-resourcename)]",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "[parameter(dotnet-eng-appinsights-subscriptionid)]",
     "subscriptions": [
      "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
      "cab65fc3-d077-467d-931f-3932eabf36d3"
     ]
    }
   ]
  },
  {
   "title": "Maestro Failed Requests/Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "let r = requests | where $__timeFilter(timestamp);\nlet f = toscalar(r | summarize min(timestamp));\nlet t = toscalar(r | summarize max(timestamp));\nlet span=(t - f)/60;\nlet interval=case(span >= 1d, bin(span, 1d), span >= 1h, bin(span, 1h), 15m);\nlet intervalHours = interval / 1h;\nr\n| where success == false and toint(resultCode) >= 500\n| make-series valueCount=count() default=0 on timestamp in range(f, t, interval) by resultCode\n| mv-expand timestamp to typeof(datetime), valueCount to typeof(double)\n| project timestamp, failuresCount=valueCount/intervalHours, resultCode",
      "resource": "[parameter(maestro-appinsights-resourcepath)]",
      "resultFormat": "time_series",
      "workspace": "[parameter(default-workspace-resourcepath)]"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "performanceCounters/exceptionsPerSecond",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "[parameter(maestro-appinsights-resourcegroup)]",
      "resourceName": "[parameter(maestro-appinsights-resourcename)]",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "[parameter(dotnet-eng-appinsights-subscriptionid)]",
     "subscriptions": [
      "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
      "cab65fc3-d077-467d-931f-3932eabf36d3"
     ]
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "alias": "{{ availabilityresult/location }}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "availabilityResult/location", "filter": "", "operator": "eq" }
      ],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "availabilityResults/availabilityPercentage",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "[parameter(grafana-appinsights-resourcegroup)]",
      "resourceName": "[parameter(grafana-appinsights-resourcename)]",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "[parameter(grafana-appinsights-subscriptionid)]",
     "subscriptions": [
      "a4fc5514-21a9-4296-bfaf-5c7ee7fa35d1",
      "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
      "cab65fc3-d077-467d-931f-3932eabf36d3"
     ]
    }
   ]
  },
  {
   "title": "DotNetEng Status Failed Requests/Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "let r = requests | where $__timeFilter(timestamp);\nlet f = coalesce(toscalar(r | summarize min(timestamp)), ago(1d));\nlet t = coalesce(toscalar(r | summarize max(timestamp)), now());\nlet span=(t - f)/60;\nlet interval=case(span >= 1d, bin(span, 1d), span >= 1h, bin(span, 1h), 15m);\nlet intervalHours = interval / 1h;\nr\n| where success == false\n| make-series kind=nonempty valueCount=count() default=0 on timestamp in range(f, t, interval)\n| mv-expand timestamp to typeof(datetime), valueCount to typeof(double)\n| project timestamp, failuresCount=valueCount/intervalHours",
      "resource": "[parameter(dotneteng-status-appinsights-resourcepath)]",
      "resultFormat": "time_series",
      "workspace": "[parameter(default-workspace-resourcepath)]"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "[parameter(dotnet-eng-appinsights-subscriptionid)]",
     "subscriptions": [
      "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
      "cab65fc3-d077-467d-931f-3932eabf36d3"
     ]
    }
   ]
  },
  {
   "title": "Helix AutoScaler Service Traces",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "[parameter(emptystring)]"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Count",
      "alias": "{{cloud/RoleName}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       {
        "dimension": "cloud/roleName",
        "filter": "fabric:/Helix/AutoScaleActorService",
        "operator": "eq"
       }
      ],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "traces/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "[parameter(dotnet-eng-appinsights-resourcegroup)]",
      "resourceName": "[parameter(dotnet-eng-appinsights-resourcename)]",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "100"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "[parameter(dotnet-eng-appinsights-subscriptionid)]",
     "subscriptions": [
      "68672ab8-de0c-40f1-8d1b-ffb20bd62c0f",
      "cab65fc3-d077-467d-931f-3932eabf36d3"
     ]
    }
   ]
  },
  {
   "title": "Maestro Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "exceptions/count",
      "metricNamespace": "Microsoft.Insights/components",
      "resourceGroup": "[parameter(maestro-appinsights-resourcegroup)]",
      "resourceName": "[parameter(maestro-appinsights-resourcename)]",
      "timeGrain": "auto",
      "top": "10"
     },
     "subscription": "cab65fc3-d077-467d-931f-3932eabf36d3"
    },
    {
     "azureLogAnalytics": {
      "query": "exceptions\r\n| where $__timeFilter(timestamp)\r\n| summarize count=count() by bin(timestamp, $__interval), problemId\r\n| order by timestamp asc",
      "resource": "[parameter(maestro-appinsights-resourcepath)]"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "[parameter(dotnet-eng-appinsights-subscriptionid)]"
    }
   ]
  }
 ]
}