{
 "title": "DNCEngChatBot",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Application Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "requests/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-appinsights-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-appinsights-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 9 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-appinsights-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "Server Response Time",
   "type": "gauge",
   "description": "Average",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "requests/duration",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-appinsights-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "Server Request Rate",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "requests/rate",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-appinsights-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  { "title": "App Service (Explore24ChatBot)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "Requests",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-appservice-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "AppConnections",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-appservice-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "histogram",
   "description": "Average",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "HttpResponseTime",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-appservice-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "Data In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "BytesReceived",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-appservice-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "Data Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "BytesSent",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-appservice-resourcegroup)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 46 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "CpuTime",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-appservice-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "http server errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 55 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "Http5xx",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-appservice-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "http 2xx",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 55 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "Http2xx",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-appservice-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "http 3xx",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 55 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "Http3xx",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chabot-appservice-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "http 403",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 65 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "Http403",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-appservice-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "http 404",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 65 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "Http404",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-appservice-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "http 4xx",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 65 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "Http4xx",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-appservice-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "Cognitive Services (testing bot, OpenAI)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 }
  },
  {
   "title": "Availability Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.CognitiveServices/accounts",
      "metricName": "SuccessRate",
      "metricNamespace": "Microsoft.CognitiveServices/accounts",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-cognitiveservices-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "Azure OpenAi Requests ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.CognitiveServices/accounts",
      "metricName": "AzureOpenAIRequests",
      "metricNamespace": "Microsoft.CognitiveServices/accounts",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-cognitiveservices-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "Total Calls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 84 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.CognitiveServices/accounts",
      "metricName": "TotalCalls",
      "metricNamespace": "Microsoft.CognitiveServices/accounts",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-cognitiveservices-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "Successful Calls ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.CognitiveServices/accounts",
      "metricName": "SuccessfulCalls",
      "metricNamespace": "Microsoft.CognitiveServices/accounts",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-cognitiveservices-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 93 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.CognitiveServices/accounts",
      "metricName": "TotalErrors",
      "metricNamespace": "Microsoft.CognitiveServices/accounts",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-cognitiveservices-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  { "title": "Storage Account", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "Availability",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-storageaccount-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "Transactions",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-storageaccount-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "timeseries",
   "description": "Data coming into the storage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "Ingress",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-storageaccount-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  },
  {
   "title": "Egress",
   "type": "timeseries",
   "description": "Data going out of the storage ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "Egress",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "[parameter(chatbot-resourcegroup)]",
      "resourceName": "[parameter(chatbot-storageaccount-resourcename)]",
      "timeGrain": "auto"
     },
     "subscription": "[parameter(chatbot-appinsights-subscriptionid)]"
    }
   ]
  }
 ]
}